### ISSUE TITLE
Random Errors while triggering jobs

### ISSUE THREAD

**Issue by chenele** [Mondtic/build-jenkins-job#8]
Hi

we use this Action to trigger jenkins jobs.

 ```
 - name: Deploy to STG
        uses: Mondtic/build-jenkins-job@master
        id: deployment_stg
        env:
          EL_ENV: stg
        continue-on-error: true
        with:
          jenkins-url: "https:/myjenkinsurl/"
          jenkins-token: ${{ secrets.TOKEN }}
          jenkins-user: ${{ env.USER }}
          jenkins-job: "build-job"
          jenkins-job-params: '{"env":"${{ env.env}}", "APP":"${{ env.COMPONENT_NAME }}", "VERSION":"${{ env.VERSION }}"}'
          jenkins-wait-job: "wait"
```
          
                 
we get the following error randomly:
```
Traceback (most recent call last):
  File "/build_job.py", line 35, in <module>
    build_number = finder.number()
  File "/src/apps/Jenkins/Application/Find/BuildFinder.py", line 13, in number
    return self.repository.get_number()
  File "/src/apps/Jenkins/Infrastructure/ServerJenkinsRepository.py", line 30, in get_number
    while "executable" not in (info := self.__get_queue_info()):
  File "/src/apps/Jenkins/Infrastructure/ServerJenkinsRepository.py", line 26, in __get_queue_info
    info = requests.get(url).json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)       
```

based on the error seems like sometimes it failed to fetch the build number of the job it triggered.
in the background the job did triggered and also completed succesfully.
Someone else encountered this?
10x

**Comment by Alec4r** [comment]
@chenele we have already added the feature to see the build number, however, we are working on triggering your issue but it hadn't been possible.
